# Generated by Django 4.0.6 on 2022-10-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product.jpg', upload_to='product_pics'),
        ),
    ]
